CBIIT/crdc-ctdc-backend

- src/main/resources/yaml/es_indices_ctdc.yml
The error came from a problem in the last PR that reverted some changes the were made to the trails page
> me and Nahom fixed trail page Error

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
Change Query Property from "snomed_disease_code" to "stage_of_disease" under Explore Tables(`Participants`,  `Biospecimens`, `Files`)
Related Ticket: [CTDC-1091](https://tracker.nci.nih.gov/browse/CTDC-1091)
> Change Query Property from "snomed_disease_code" to "stage_of_disease"

- src/main/resources/graphql/crdc-ctdc-es-full.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
- src/main/resources/yaml/facet_search_es.yml
- src/main/resources/yaml/single_search_es.yml
Fixes participant count for participant Tab, and the counts for widgets and facets
> Bug fixes for Explore page

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
- src/main/resources/yaml/single_search_es.yml
- Simplified Indices and removed Unions
- Changed indice source in single search
- Added filters in graphQL Private ES
> Bug fixes for adding Cart data

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
Update the query to provide more fields into fileOverView query as this query can be use for download manifest function.
> update fileOverView query

- src/main/resources/yaml/es_indices_ctdc.yml
- src/main/resources/yaml/facet_search_es.yml
- src/main/resources/yaml/single_search_es.yml
Fixed issues with Biospecimen facets not matching biospecimen tab counts
> Fixed issues with Biospecimen facets not matching biospecimen tab counts

- src/main/resources/application.properties
- Revert accidental change made to application.properties in the last PR: https://github.com/CBIIT/crdc-ctdc-backend/pull/27
> Revert accidental change made to application.properties

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
- src/main/resources/yaml/global_search_es.yml
- Updated `age_at_diagnosis` to `age_at_enrollment`
- Fixed sorting by making `age_at_enrollment` to be a `Float` from `String` and Changing `age_at_enrollment` from `Keyword` to `integer` in the `es_indices.yml` file
- Removed `collect/[]` from diagnosis property
> Data updates

- src/main/resources/yaml/es_indices_ctdc.yml
Added distinct count of disease types to homepage
> Added distinct count of disease types to homepage

- src/main/resources/yaml/global_search_es.yml
- src/main/resources/yaml/public_global_search_es.yml
Change property name to wildcard for GS
> Change property name to wildcard for GS

- src/main/resources/yaml/es_indices_ctdc.yml
Fixed study_specimen index to output the correct number of sample_count
> CTDC-966: Studies page

- src/main/resources/yaml/es_indices_ctdc.yml
Removed collect from carcinogen_exposure and indented
> Removed collect from carcinogen_exposure and indented

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
- src/main/resources/yaml/global_search_es.yml
To fix the issue of a many to many autocomplete issue by adding a list of results the FE can grab from to give the user non repeating autocomplete results
> GS Autocomplete fix

- src/main/resources/yaml/es_indices_ctdc.yml
Updated the Indices to combine all autocomplete results
> Updated the Indices to combine all autocomplete results to

- src/main/resources/yaml/es_indices_ctdc.yml
- src/main/resources/yaml/facet_search_es.yml
changed the counts for targeted therapy and also changed the counts for specimen_Id to parent_specimen_id to work with the new data
> Changed count variables to line up with new data

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/global_search_es.yml
Changed counts and biospecimen title cards to use parent_specimen_id
> Changed counts and biospecimen title cards to use parent_specimen_id

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
Added new indices for study file collection
added GraphQL to add it
> Added new indices for study file collection

- src/main/resources/yaml/es_indices_ctdc.yml
- src/main/resources/yaml/facet_search_es.yml
https://tracker.nci.nih.gov/browse/CTDC-1477
and
https://tracker.nci.nih.gov/browse/CTDC-1476
> Ctdc 1476 and fixing hero file count

- src/main/resources/yaml/es_indices_ctdc.yml
Added small change to indices so to removes the empty targeted therapy
https://tracker.nci.nih.gov/browse/CTDC-1476
> Added small change to indices

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
- src/main/resources/yaml/single_search_es.yml
Bug fix for biospecimen tab selected files not adding to cart
https://tracker.nci.nih.gov/browse/CTDC-1503
> Bug fix for biospecimen tab selected files not adding to cart

- src/main/resources/yaml/es_indices_ctdc.yml
Adds more variables to the stats bar so the Therapy_count index can filter it on the front end.
> Bug fix for targeted therapy count on the stats bar

- pom.xml
vulnerability fix  [CVE-2023-20883] upgrade spring boot version 
https://tracker.nci.nih.gov/browse/CTDC-1193
> vulnerability fix  [CVE-2023-20883] upgrade spring boot version

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
- src/main/resources/yaml/facet_search_es.yml
added PrimaryDiagnosisDiseaseGroup to the backend
Ticket: https://tracker.nci.nih.gov/browse/CTDC-1354
> added PrimaryDiagnosisDiseaseGroup to the backend

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
adding Study_short_name to file manifest
> adding Study_short_name to file manifest

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/single_search_es.yml
Create backend support for interoperation adding studiesByProgram to interface with the ICDC interoperation service
https://tracker.nci.nih.gov/browse/CTDC-1598
> Create backend support for interoperation

- src/main/java/gov/nih/nci/bento_ri/model/PrivateESDataFetcher.java
- src/main/resources/graphql/bento-extended-doc.graphql
- src/main/resources/graphql/bento-extended.graphql
- src/main/resources/graphql/crdc-ctdc-es-full.graphql
- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_bento.yml
- src/main/resources/yaml/es_indices_ctdc.yml
- src/main/resources/yaml/facet_search_es.yml
- src/main/resources/yaml/global_search_es.yml
Hot fix to remove gender
https://tracker.nci.nih.gov/browse/CTDC-1619
> CTDC-1619: Hot fix to remove gender

- src/main/resources/graphql/crdc-ctdc-es-full.graphql
- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
- src/main/resources/yaml/facet_search_es.yml
- src/main/resources/yaml/global_search_es.yml
- src/main/resources/yaml/public_global_search_es.yml
- src/main/resources/yaml/single_search_es.yml
https://tracker.nci.nih.gov/browse/CTDC-1604
> CTDC-1604 for 1.0.1

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
Ticket : https://tracker.nci.nih.gov/browse/CTDC-1637
> Participants page

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
- src/main/resources/yaml/es_indices_ctdc.yml
counts all files that are not the study file
> add in file count to the study_page

- src/main/resources/graphql/crdc-ctdc-private-es.graphql
adding unique_repository  as requested from CTDC-1548->requirement # 11
> CTDC-1548: add unique_repository to the stopgap code
